name: CI

on:
  push:
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        run: npm i -g pnpm@latest

      - name: Install
        run: |
          pnpm install

      - name: Build
        run: |
          set -e
          pnpm build
